[package]
name = "ch32v-rt"
version = "0.0.0"
edition = "2021"
authors = ["Andelf <andelf@gmail.com>"]
repository = "https://github.com/andelf/ch32v-rt"
documentation = "https://docs.rs/ch32v-rt"
homepage = "https://github.com/andelf/ch32v-rt"
categories = []
description = "Placeholder for ch32v-rt, managed by the ch32-rt team"
keywords = []
readme = "README.md"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ch32v-rt-macros = { path = "ch32v-rt-macros", version = "0.1.0" }


[workspace]
members = ["ch32v-rt-macros"]
